### ISSUE TITLE
Include Phinx migrations from extensions

### ISSUE THREAD

**Issue by stevenrombauts** [joomlatools/joomlatools-platform#318]
Right now we expect all migrations to be in the `install/mysql/migrations` directory. This does not yet include extension migrations.

It should be possible to include multiple paths and look for a common directory in every extension, so we can also create migrations files per release. We could read these from the `vendor` directory.

**Comment by johanjanssens** [comment]
@stevenrombauts What about symlinking? Could we symlink the paths for extensions into this path to Phinx can find them there?

**Comment by stevenrombauts** [comment]
@johanjanssens Phinx has built-in support for multiple paths, so something like this should work:

```yaml
paths:
    migrations:
      - %%PHINX_CONFIG_DIR%%/install/mysql/migrations
      - %%PHINX_CONFIG_DIR%%/app/administrator/components/com_*/resources/install/migrations
```

That will expand to all component directories that have the migrations directory in it. Tested this real quick locally and it works great. No need for any manual setup then.
